# Local connections
local   all             all                                     trust
host    all             all             0.0.0.0/0               md5

# Replication connections
host    replication     replicator      0.0.0.0/0               md5
